name: weather_icons
description: Icons from https://github.com/erikflowers/weather-icons
environment:
  sdk: ^2.0.0-alpha.121
dependencies:
  png-tools:
    url: github.com/toitware/toit-png-tools
    version: ^1.0.0
